# Dockerfile-angular

# Use Node.js image
FROM node:20-alpine AS build

# Set working directory
WORKDIR /app

COPY package.json ./

RUN npm cache clean --force

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Erstellen Sie das Angular-Build
RUN npm run build --prod

# Schritt 2: Bereitstellen des Builds
# Verwenden Sie ein leichtes Webserver-Image
FROM nginx:alpine

# Kopieren Sie das Build-Artefakt von der vorherigen Stage
COPY --from=build /app/dist/quiz-app /usr/share/nginx/html

EXPOSE 80

# Start the Angular app
CMD ["nginx", "-g", "daemon off;"]